#include <stdint.h>
#include <stdlib.h>

#include "sfunc.h"

#include <stm32l011xx.h>
#include <stm32l0xx_hal.h>
#include <stm32l0xx_hal_rcc.h>
#include <stm32l0xx_hal_gpio.h>
#include <stm32l0xx_nucleo_32.h>

const char msg[] = "Hello from nucleo_l011k4 !";

volatile __attribute__((used)) uint32_t var1 = 0x12345678U;
volatile __attribute__((used, section(".noinit"))) uint32_t var2;

#define HSI_VALUE    ((uint32_t)16000000U) /*!< Value of the Internal oscillator in Hz*/

void SysTick_Handler(void)
{
	HAL_IncTick();
}

void Error_Handler(void)
{
	while (1);
}

/* generated by STM32Cube */
uint32_t SystemCoreClock = 2097152U; /* 32.768 kHz * 2^6 */
const uint8_t AHBPrescTable[16] = { 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U, 1U, 2U, 3U, 4U, 6U, 7U, 8U, 9U };
const uint8_t APBPrescTable[8] = { 0U, 0U, 0U, 0U, 1U, 2U, 3U, 4U };
const uint8_t PLLMulTable[9] = { 3U, 4U, 6U, 8U, 12U, 16U, 24U, 32U, 48U };

uint32_t i = 0xAA;

void HAL_MspInit(void)
{
	__HAL_RCC_SYSCFG_CLK_ENABLE();
	__HAL_RCC_PWR_CLK_ENABLE();

}

int main(void)
{
	HAL_Init();

	__HAL_RCC_GPIOC_CLK_ENABLE();
	__HAL_RCC_GPIOA_CLK_ENABLE();
	__HAL_RCC_GPIOB_CLK_ENABLE();

	GPIO_InitTypeDef cfg = {
		.Pin = LED3_PIN,
		.Mode = GPIO_MODE_OUTPUT_PP,
		.Pull = GPIO_NOPULL,
		.Speed = GPIO_SPEED_FREQ_LOW
	};

	HAL_GPIO_Init(LED3_GPIO_PORT, &cfg);

	for (;;) {
		HAL_Delay(1000);
		HAL_GPIO_WritePin(LED3_GPIO_PORT, LED3_PIN, GPIO_PIN_SET);
		HAL_Delay(1000);
		HAL_GPIO_WritePin(LED3_GPIO_PORT, LED3_PIN, GPIO_PIN_RESET);

		i = _sinc(i);
	}
}